### ISSUE TITLE
Add ability to toggle Wordpress Editor for CPTs

### ISSUE THREAD

**Issue by NomeQ** [Trillium-Solutions/transit-custom-posts#33]
Most of our sites only use structured meta fields for route pages, so it would be nice to have an option with the TCP settings page to enable/disable the Wordpress Editor for post types. That way, clients won't be confused and try to add text that isn't even used by the theme.

**Comment by sleddd** [comment]
@NomeQ  I added separate options to disable the routes, alerts, or timetable editor. I did not allow for an option to disable Board meetings as it seemed relevant to keep that editor for extended descriptions or special notes. I added separate options for each CPT, because some may want an alerts editor, but not a timetable editor etc.. Let me know if you need additional changes.

**Comment by NomeQ** [comment]
Sounds great! Thanks!
