### ISSUE TITLE
Do Board Meetings make sense as a custom post type?

### ISSUE THREAD

**Issue by trilliumtransit** [Trillium-Solutions/transit-custom-posts#5]
We use them a lot for Trillium sites, but do they really make sense as part of the this plugin? Quite possibly they should be reserved for an internal fork because we use them so much, but they seem a little inconsistent with the rest of the plugin. 

Any opinions? Should we remove them entirely?

**Comment by NomeQ** [comment]
Having now made 3 sites using my plugin, I am going to go with a resounding "no".

I am going to remove board meetings from the plugin.

**Comment by thomastrillium** [comment]
I'm surprised by this and from the optics point of view I'm very opposed. This is a good selling point to agencies.

What's the technical reason?

**Comment by NomeQ** [comment]
From a development standpoint it makes no sense to include, and semantically it doesn't make a lot of sense either.

- Including board meetings as a custom post type doesn't save much in terms of development effort. It's still necessary to create a custom template in the theme to display them, and, because a board meeting isn't a standardized type of data like GTFS, clients generally want very different implementations and fields.
- The above generally means that we need to integrate with another plugin such as ACF to add the custom fields to board meetings.
- We can generally get a better implementation for board meetings by using existing, well-supported, easy-to-use plugins, and including them in the plugin saves us no time or effort.
- Semantically, it doesn't make a lot of sense because alerts, timetables, and routes are all linked by GTFS fields, and all complement each other. Board meetings are just a custom post type many of our clients like. They do not benefit in terms of development effort from being included in the plugin, nor do they interact with any of the other custom post types.

**Comment by thomastrillium** [comment]
All this is true. Let's still hold though. Let me mull.

**Comment by sleddd** [comment]
The plugin now has a board meeting CPT option.
