### ISSUE TITLE
Turn routes off based on timetables

### ISSUE THREAD

**Issue by danielleogden** [Trillium-Solutions/transit-custom-posts#56]
As Evan suggested last week, I think we want to consider how we can manage routes on the website by looking at whether timetables exist for that route, rather than whether the route is present in the routes.txt. This will save time for both Support and Website team by not having to update and re-export the GTFS feed to make adjustments.

Let's consider adding a simple function that turns a route off if timetables are not found.

CATA exception:
I would also like to have an option to override this functionality for certain routes. For example, CATA only wants to show routes that are currently in service--except for the 3 summer routes. They'd like the summer route pages to be visible even though they are not quite in service yet. YARTS is another client that may need that functionality. Let's factor this into our solution. 

CATA wants to go live June 23. Do you think we could prioritize this ticket so we can have this working in time for launch? 

Tagging @ekeaton and @evantrillium if you have additional input

**Comment by chancecorbeil** [comment]
Sure, I will prioritize this ticket. I appreciate the descriptive outline of this task. Very helpful in conceptualizing the goal.

**Comment by chancecorbeil** [comment]
Do you have an example of a GTFS feed url that emulates this situation? I would like to know how the txt files are structured when timetables are not present for a route. 

I believe we can use route_ids to identify if there are no timetables for a route. If a route's route_id is not a match for any timetable's route_id, then there are no timetables for that route.

**Comment by ekeaton** [comment]
@chancecorbeil Any feed will work! Yes route_ids are used to identify which timetables match to which Route. So right now if timetables are expired then we just have an "empty" route page. So the solution will need to deal with removing the Route post if no timetables are expired. If you look here in TCP https://github.com/Trillium-Solutions/transit-custom-posts/blob/production/gtfs-update.php on line 125 it shows how the Route posts are created from Routes.txt. Which is fine, except for when that Route needs to be removed from the Route posts. Right now Support has to toggled it off within the GTFS to remove it from Routes.txt. So when TCP is run again it's no longer a part of that file and no longer appears as a route post. We'd like to avoid that and instead create a function that removes a Route post if timetables are expired. 

Hope that makes more sense!

**Comment by evantrillium** [comment]
For YARTS and CATA we can just set the timetables start_date and end_date to *not* match the service dates as described in the GTFS.

This is easy enough - we just determine "is this a route that's always on" Y/N and if Y then it's start_date is like, 2000-01-01 and end date is 2100-01-01.

This is what I did for YARTS' imap

**Comment by ekeaton** [comment]
@chancecorbeil I thought of another edge case. This new function will need to remove/"draft" routes that do not have an associated timetable. So two things: It will need to:

1. Draft/remove the route post when the timetable/s for a route expires aka looking at the timetable end date. 2. Draft/remove a route if there are no timetables that are using its route id. (Since timetables appear on route pages according to which route id they match too)

**Comment by chancecorbeil** [comment]
@ekeaton Thanks! I appreciate you identifying edge cases.

The good news is this situation is what I originally thought was the main goal, so it's already built in. Woohoo!

**Comment by chancecorbeil** [comment]
We have a working version of this feature.

Routes with missing or expired timetables are moved to the trash. This feature can be overridden on a route by route basis from the route WP editor. Updating the field ‘Keep route published if there are no timetables’ to ‘yes’ will keep routes with missing or expired timetables from moving to the trash.

This feature has a high bug potential, so it’s worth us testing out many use cases.

**Tests**
Run GTFS update using GTFS feed source:  http://data.trilliumtransit.com/gtfs/cottonwood-az-us/cottonwood-az-us--ttable.zip
5 of 6 routes move to trash to pass.
Add a route with no route id. Moves to trash to pass.
Add a route with a route id that doesn’t match a timetable. Moves to trash to pass.
Select an active route and update the associated timetables to an end date that is in the past. Moves to trash to pass.
Any of the above situations, select a route and update the field ‘Keep route published if there are no timetables’ to ‘yes’. Now the route should remain published to pass.

One of the use cases fails and I’m currently looking for an easy solution. Once routes are in the trash, they can’t be edited. Also we can’t remove routes from the trash because the function puts them right back in the trash. So we can’t update the ‘Keep route published if there are no timetables’ field of an imported route. I will work on this task next week.

**Comment by chancecorbeil** [comment]
I've decided to make this feature optional. We will use the settings page to toggle this feature on and off.

This change will solve use cases like 
1. NWOTA not having timetables
2. Once routes are in the trash, they can’t be edited. Also we can’t remove routes from the trash because the function puts them right back in the trash. So we can’t update the ‘Keep route published if there are no timetables’ field of an imported route.

**Comment by chancecorbeil** [comment]
This feature is now optional! The current version of this feature passes all my tests.
